%%-*- mode: erlang -*-

DEPS = case lists:keyfind(deps, 1, CONFIG) of
          {_, Deps} -> Deps;
          _ -> []
      end,

UrlPrefix = "https://github.com/emqx/",

EMQX_DEP = {emqx, {git, UrlPrefix ++ "emqx", {tag, "4.2.9"}}},
EMQX_MGMT_DEP = {emqx_management, {git, UrlPrefix ++ "emqx-management", {tag, "4.2.9"}}},

NewDeps = [EMQX_DEP, EMQX_MGMT_DEP | DEPS],

CONFIG1 = lists:keystore(deps, 1, CONFIG, {deps, NewDeps}),

CONFIG1.
